title: Helena Chi # your name (or website title) here
logo: "/images/helena.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Geospatial data scientist 
  <br><br>
  Masters of IA '24
  <br><br>
  University of California, San Diego
  <br><br>
  <a href="mailto:chizhiyuan435@gmail.com">Say hello</a>
  <br><br>
  <a href="https://www.linkedin.com/in/zhiyuan-chi/">LinkedIn</a> 
  <br><br>
  <a href="https://github.com/ZhiyuanChi">Github</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-4HV6XPV8S2 # your Google Analytics tracking ID here
